### ISSUE TITLE
Wrong running

### ISSUE THREAD

**Issue by nancheng58** [SocialRecsys/SMIN#1]
Hello,when i prepare for dataset using your code and run main.py with CiaoDVD datasets,it happens
```
Traceback (most recent call last):
  File "main.py", line 352, in <module>
    hope.run()
  File "main.py", line 277, in run
    epoch_loss = self.trainModel()
  File "main.py", line 222, in trainModel
    res = self.ui_informax(self.allEmbed, self.ui_subGraphAdj, self.ui_subGraphAdj_Tensor,self.ui_subGraphAdj_Norm)
  File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yangjiyuan-slurm/SMIN/MV_MIL/informax.py", line 57, in forward
    positive = self.encoder(features, corrupt=False)
  File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yangjiyuan-slurm/SMIN/MV_MIL/informax.py", line 22, in forward
    features = self.conv(features)
  File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yangjiyuan-slurm/SMIN/MV_MIL/gcn.py", line 21, in forward
    h = self.layer(self.g, h)
  File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yangjiyuan-slurm/SMIN/MV_MIL/graphconv.py", line 62, in forward
    graph.srcdata['h'] = feat
  File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/dgl/view.py", line 65, in __setitem__
    self._graph.set_n_repr({key : val}, self._nodes)
  File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/dgl/graph.py", line 2280, in set_n_repr
    raise DGLError('Expect number of features to match number of nodes (len(u)).'
dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 108306 and 108191 instead.
```
Look forward to your reply.

**Comment by xiaolingcom** [comment]
Sorry I forgot my account password, you need to run ‘python ./dataset/CiaoDVD/GenerateSubGraph.py’ again to generate a new  2hop_ui_subGraph.pkl file，hope you go well.

**Comment by xiaolingcom** [comment]
> Hello,when i prepare for dataset using your code and run main.py with CiaoDVD datasets,it happens
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 352, in <module>
>     hope.run()
>   File "main.py", line 277, in run
>     epoch_loss = self.trainModel()
>   File "main.py", line 222, in trainModel
>     res = self.ui_informax(self.allEmbed, self.ui_subGraphAdj, self.ui_subGraphAdj_Tensor,self.ui_subGraphAdj_Norm)
>   File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/yangjiyuan-slurm/SMIN/MV_MIL/informax.py", line 57, in forward
>     positive = self.encoder(features, corrupt=False)
>   File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/yangjiyuan-slurm/SMIN/MV_MIL/informax.py", line 22, in forward
>     features = self.conv(features)
>   File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/yangjiyuan-slurm/SMIN/MV_MIL/gcn.py", line 21, in forward
>     h = self.layer(self.g, h)
>   File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/yangjiyuan-slurm/SMIN/MV_MIL/graphconv.py", line 62, in forward
>     graph.srcdata['h'] = feat
>   File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/dgl/view.py", line 65, in __setitem__
>     self._graph.set_n_repr({key : val}, self._nodes)
>   File "/data/yangjiyuan-slurm/anaconda3/envs/torch1.5/lib/python3.8/site-packages/dgl/graph.py", line 2280, in set_n_repr
>     raise DGLError('Expect number of features to match number of nodes (len(u)).'
> dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 108306 and 108191 instead.
> ```
> 
> Look forward to your reply.

Sorry,  I forgot my account password, you need to run ‘python ./dataset/CiaoDVD/GenerateSubGraph.py’ again to generate a new 2hop_ui_subGraph.pkl file，hope you go well.

**Comment by nancheng58** [comment]
I havd deployed the lastest code and it ran correctly. Thanks to your work very much!

**Comment by yingy06** [comment]
Hello Author, when I prepare for dataset using your code and run main.py with CiaoDVD datasets,it happens
Traceback (most recent call last):
  File "D:/下载/SMIN-main/SMIN-main/main.py", line 349, in <module>
    hope = Hope(args,data,metaPath,subGraph)
  File "D:/下载/SMIN-main/SMIN-main/main.py", line 54, in __init__
    self.uu_graph = dgl.graph(self.metaPath['UU'], ntype='user', etype='social')
  File "D:\DELL\ANACONDA\envs\PyTorch\lib\site-packages\dgl\convert.py", line 161, in graph
    raise DGLError('The ntype argument is deprecated for dgl.graph. To construct ' \
dgl._ffi.base.DGLError: The ntype argument is deprecated for dgl.graph. To construct a graph with named node types, use dgl.heterograph.
I'm sorry to bother you. I would be honored if you could reply to me

**Comment by yingy06** [comment]
Hello Author, when I prepare for dataset using your code and run main.py with CiaoDVD datasets,it happens
Traceback (most recent call last):
File "D:/下载/SMIN-main/SMIN-main/main.py", line 349, in
hope = Hope(args,data,metaPath,subGraph)
File "D:/下载/SMIN-main/SMIN-main/main.py", line 54, in init
self.uu_graph = dgl.graph(self.metaPath['UU'], ntype='user', `etype='social')`
File "D:\DELL\ANACONDA\envs\PyTorch\lib\site-packages\dgl\convert.py", line 161, in graph
raise DGLError('The ntype argument is deprecated for dgl.graph. To construct '
dgl._ffi.base.DGLError: The ntype argument is deprecated for dgl.graph. To construct a graph with named node types, use dgl.heterograph.
I'm sorry to bother you. I would be honored if you could reply to `me```
